on: [push]

jobs:
  coligo_job:
    runs-on: ubuntu-latest
    name: build and deploy coligo service
    steps:
    - name: build and deploy 
      id: coligo
      uses: no9/coligo-action@1.1.0
      with:
        project: 'sample-app'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.coligo.outputs.time }}"
